# baseURL
@baseURL = http://localhost:3000

GET http://localhost:3000

###
# err url
GET http://localhost:3000/sdf

###
# User Signup
POST {{ baseURL }}/signup
Content-Type: application/json

{
    "email": "example@email.com",
    "password": "password"
}
